# These are supported funding model platforms

github: sokratis12GR
patreon: sokratis12GR
open_collective: # Replace with a single Open Collective username
ko_fi: sokratis12GR
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: paypal.me/sokratis12GR
