plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.146'
    id 'idea'
}

version = mod_version
group = mod_group_id
base { archivesName = mod_id }
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = 'https://www.cursemaven.com'; content { includeGroup 'curse.maven' } }
    maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
}

neoForge {
    version = project.neo_version
    accessTransformers = project.files('src/main/resources/META-INF/armorplus_at.cfg')
    runs {
        client { client() }
        server { server(); programArgument '--nogui' }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').absolutePath, '--existing', file('src/main/resources/').absolutePath
        }
        configureEach { logLevel = org.slf4j.event.Level.DEBUG }
    }
    mods { "${mod_id}" { sourceSet(sourceSets.main) } }
}

configurations { runtimeClasspath.extendsFrom localRuntime }

dependencies {
    implementation "curse.maven:thedragonlib-248055:5505781"
    implementation 'software.bernie.geckolib:geckolib-neoforge-1.21.1:4.8.2'
    compileOnly "curse.maven:jei-238222:8857687"
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
        minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
        neo_version: neo_version, neo_version_range: neo_version_range, loader_version_range: loader_version_range,
        mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
        mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) { expand replaceProperties + [project: project] }
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }

publishing {
    publications { register('mavenJava', MavenPublication) { from components.java } }
    repositories { maven { url "file://${project.projectDir}/mcmodsrepo" } }
}
