plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.147'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_name
}

tasks.named('jar', Jar).configure {
    archiveFileName = "${mod_id}-${minecraft_version}-${mod_version}-neo.jar"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets.main.resources {
    srcDir 'src/generated/client'
    srcDir 'src/generated/server'
}

neoForge {
    version = neoforge_version
    validateAccessTransformers = true

    runs {
        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }

        gameTestServer {
            type = "gameTestServer"
        }

        clientData {
            clientData()
            programArguments.addAll '--mod', mod_id,
                    '--all',
                    '--output', file('src/generated/client').absolutePath,
                    '--existing', file('src/main/resources').absolutePath
        }

        serverData {
            serverData()
            programArguments.addAll '--mod', mod_id,
                    '--all',
                    '--output', file('src/generated/server').absolutePath,
                    '--existing', file('src/main/resources').absolutePath
        }
    }

    mods {
        armorplus {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://cursemaven.com'; content { includeGroup 'curse.maven' } }
}

dependencies {
    implementation "curse.maven:thedragonlib-248055:9013506"
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
        minecraft_version: minecraft_version,
        minecraft_version_range: minecraft_version_range,
        neoforge_version: neoforge_version,
        neoforge_version_range: neoforge_version_range,
        loader_version_range: loader_version_range,
        mod_id: mod_id, mod_name: mod_name, mod_license: mod_license,
        mod_version: mod_version, mod_authors: mod_authors, mod_description: mod_description
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) { expand replaceProperties }
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }

publishing {
    publications { mavenJava(MavenPublication) { artifact jar } }
    repositories { maven { url = layout.buildDirectory.dir('repo') } }
}
