org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neoforge_version=26.1.2.82
neoforge_version_range=[26.1.2.82,)
loader_version_range=[4,)

mod_id=armorplus
mod_name=ArmorPlus
mod_license=GNU General Public License v3.0
mod_version=22.0.1
curseforge_project_id=237366
mod_group_id=com.sofodev.armorplus
mod_authors=sokratis12GR
mod_description=ArmorPlus adds new armor sets, tools, weapons, blocks, and progression content.
