/*
 * Copyright (c) TheDragonTeam 2016-2017.
 */

package net.thedragonteam.armorplus.registry;

import net.minecraft.item.Item;

import static net.thedragonteam.armorplus.registry.ModItems.*;

public class APItems {

    public static Item coalHelmet;
    public static Item coalChestplate;
    public static Item coalLeggings;
    public static Item coalBoots;
    public static Item lapisHelmet;
    public static Item lapisChestplate;
    public static Item lapisLeggings;
    public static Item lapisBoots;
    public static Item redstoneHelmet;
    public static Item redstoneChestplate;
    public static Item redstoneLeggings;
    public static Item redstoneBoots;
    public static Item emeraldHelmet;
    public static Item emeraldChestplate;
    public static Item emeraldLeggings;
    public static Item emeraldBoots;
    public static Item obsidianHelmet;
    public static Item obsidianChestplate;
    public static Item obsidianLeggings;
    public static Item obsidianBoots;
    public static Item lavaHelmet;
    public static Item lavaChestplate;
    public static Item lavaLeggings;
    public static Item lavaBoots;
    public static Item chickenHelmet;
    public static Item chickenChestplate;
    public static Item chickenLeggings;
    public static Item chickenBoots;
    public static Item slimeHelmet;
    public static Item slimeChestplate;
    public static Item slimeLeggings;
    public static Item slimeBoots;
    public static Item guardianHelmet;
    public static Item guardianChestplate;
    public static Item guardianLeggings;
    public static Item guardianBoots;
    public static Item superStarHelmet;
    public static Item superStarChestplate;
    public static Item superStarLeggings;
    public static Item superStarBoots;
    public static Item enderDragonHelmet;
    public static Item enderDragonChestplate;
    public static Item enderDragonLeggings;
    public static Item enderDragonBoots;
    public static Item theUltimateHelmet;
    public static Item theUltimateChestplate;
    public static Item theUltimateLeggings;
    public static Item theUltimateBoots;
    public static Item cobaltHelmet;
    public static Item cobaltChestplate;
    public static Item cobaltLeggings;
    public static Item cobaltBoots;
    public static Item arditeHelmet;
    public static Item arditeChestplate;
    public static Item arditeLeggings;
    public static Item arditeBoots;
    public static Item manyullynHelmet;
    public static Item manyullynChestplate;
    public static Item manyullynLeggings;
    public static Item manyullynBoots;
    public static Item pigIronHelmet;
    public static Item pigIronChestplate;
    public static Item pigIronLeggings;
    public static Item pigIronBoots;
    public static Item knightSlimeHelmet;
    public static Item knightSlimeChestplate;
    public static Item knightSlimeLeggings;
    public static Item knightSlimeBoots;
    public static Item coalSword;
    public static Item coalBattleAxe;
    public static Item coalBow;
    public static Item lapisSword;
    public static Item lapisBattleAxe;
    public static Item lapisBow;
    public static Item redstoneSword;
    public static Item redstoneBattleAxe;
    public static Item redstoneBow;
    public static Item emeraldSword;
    public static Item emeraldBattleAxe;
    public static Item emeraldBow;
    public static Item obsidianSword;
    public static Item obsidianBattleAxe;
    public static Item obsidianBow;
    public static Item lavaSword;
    public static Item lavaBattleAxe;
    public static Item lavaBow;
    public static Item guardianSword;
    public static Item guardianBattleAxe;
    public static Item guardianBow;
    public static Item superStarSword;
    public static Item superStarBattleAxe;
    public static Item superStarBow;
    public static Item enderDragonSword;
    public static Item enderDragonBattleAxe;
    public static Item enderDragonBow;

    public APItems() {
    }

    public static void init() {
        coalHelmet = coal[0];
        coalChestplate = coal[1];
        coalLeggings = coal[2];
        coalBoots = coal[3];
        lapisHelmet = lapis[0];
        lapisChestplate = lapis[1];
        lapisLeggings = lapis[2];
        lapisBoots = lapis[3];
        redstoneHelmet = redstone[0];
        redstoneChestplate = redstone[1];
        redstoneLeggings = redstone[2];
        redstoneBoots = redstone[3];
        emeraldHelmet = emerald[0];
        emeraldChestplate = emerald[1];
        emeraldLeggings = emerald[2];
        emeraldBoots = emerald[3];
        obsidianHelmet = obsidian[0];
        obsidianChestplate = obsidian[1];
        obsidianLeggings = obsidian[2];
        obsidianBoots = obsidian[3];
        lavaHelmet = lava[0];
        lavaChestplate = lava[1];
        lavaLeggings = lava[2];
        lavaBoots = lava[3];
        chickenHelmet = chicken[0];
        chickenChestplate = chicken[1];
        chickenLeggings = chicken[2];
        chickenBoots = chicken[3];
        slimeHelmet = slime[0];
        slimeChestplate = slime[1];
        slimeLeggings = slime[2];
        slimeBoots = slime[3];
        guardianHelmet = guardian[0];
        guardianChestplate = guardian[1];
        guardianLeggings = guardian[2];
        guardianBoots = guardian[3];
        superStarHelmet = superStar[0];
        superStarChestplate = superStar[1];
        superStarLeggings = superStar[2];
        superStarBoots = superStar[3];
        enderDragonHelmet = enderDragon[0];
        enderDragonChestplate = enderDragon[1];
        enderDragonLeggings = enderDragon[2];
        enderDragonBoots = enderDragon[3];
        theUltimateHelmet = theUltimate[0];
        theUltimateChestplate = theUltimate[1];
        theUltimateLeggings = theUltimate[2];
        theUltimateBoots = theUltimate[3];

        cobaltHelmet = cobalt[0];
        cobaltChestplate = cobalt[1];
        cobaltLeggings = cobalt[2];
        cobaltBoots = cobalt[3];
        arditeHelmet = ardite[0];
        arditeChestplate = ardite[1];
        arditeLeggings = ardite[2];
        arditeBoots = ardite[3];
        manyullynHelmet = manyullyn[0];
        manyullynChestplate = manyullyn[1];
        manyullynLeggings = manyullyn[2];
        manyullynBoots = manyullyn[3];
        pigIronHelmet = pigIron[0];
        pigIronChestplate = pigIron[1];
        pigIronLeggings = pigIron[2];
        pigIronBoots = pigIron[3];
        knightSlimeHelmet = knightSlime[0];
        knightSlimeChestplate = knightSlime[1];
        knightSlimeLeggings = knightSlime[2];
        knightSlimeBoots = knightSlime[3];

        coalSword = sword[0];
        coalBattleAxe = battleAxe[0];
        coalBow = bow[0];
        lapisSword = sword[1];
        lapisBattleAxe = battleAxe[1];
        lapisBow = bow[1];
        redstoneSword = sword[2];
        redstoneBattleAxe = battleAxe[2];
        redstoneBow = bow[2];
        emeraldSword = sword[3];
        emeraldBattleAxe = battleAxe[3];
        emeraldBow = bow[3];
        obsidianSword = sword[4];
        obsidianBattleAxe = battleAxe[4];
        obsidianBow = bow[4];
        lavaSword = sword[5];
        lavaBattleAxe = battleAxe[5];
        lavaBow = bow[5];
        guardianSword = sword[6];
        guardianBattleAxe = battleAxe[6];
        guardianBow = bow[6];
        superStarSword = sword[7];
        superStarBattleAxe = battleAxe[7];
        superStarBow = bow[7];
        enderDragonSword = sword[8];
        enderDragonBattleAxe = battleAxe[8];
        enderDragonBow = bow[8];
    }
}
